### ISSUE TITLE
Host count data as h5ad

### ISSUE THREAD

**Issue by cdedonno** [snap-stanford/SATURN#1]
Hi, congratulations for the interesting work. I was wondering if you could host the count data that you used for model training as `h5ad` files, in addition to the aligned data you are already providing. 

I have seen the dataloading notebooks which explain how to generate the data, but generating these from scratch can be quite slow, especially in the case of the frog data.

**Comment by Yanay1** [comment]
Hi, thanks!

I can send them to you over google drive, could you let me know an email that would be good to share too? You can email me at 

yanay (at) stanford.edu

**Comment by Yanay1** [comment]
Resolved over email!
