### ISSUE TITLE
The pretraining process in Train SATURN does not start and no errors are shown

### ISSUE THREAD

**Issue by cam1flag** [snap-stanford/SATURN#10]
Hi,
in the cell 
```
!python3 ../../train-saturn.py --in_data=data/frog_zebrafish_run.csv --in_label_col=cell_type --ref_label_col=cell_type --num_macrogenes=2000     --hv_genes=8000  --centroids_init_path=saturn_results/fz_centroids.pkl --score_adata --ct_map_path=data/frog_zebrafish_cell_type_map.csv --work_dir=. --device_num=0
```

I only get this 

Global seed set to 0
Intel(R) Extension for Scikit-learn* enabled ([https://github.com/intel/scikit-learn-intelex](https://github.com/intel/scikit-learn-intelex?fbclid=IwAR1uy1jMG4SQNRPeb_xzk9781EK593k7YYxH_qDlJxcAA9hifaXXwSj8wB8))
Using Device 0
Set seed to 0
After loading the anndata frog View of AnnData object with n_obs × n_vars = 96935 × 9538
    obs: 'clusters', 'parent_clusters', 'cell_type', 'n_genes', 'species', 'species_type_label', 'truth_labels', 'ref_labels'
    var: 'n_cells'
After loading the anndata zebrafish View of AnnData object with n_obs × n_vars = 63371 × 16980
    obs: 'n_counts', 'unique_cell_id', 'cell_names', 'library_id', 'batch', 'ClusterID', 'ClusterName', 'TissueID', 'TissueName', 'TimeID', 'cluster', 'cell_type', 'n_genes', 'species', 'species_type_label', 'truth_labels', 'ref_labels'
    var: 'n_cells'

Obviously running the next cell gives this error 
ls: cannot access "./saturn_results": No such file or directory

Could you help?
Thanks

**Comment by Yanay1** [comment]
Sorry for the delay in reply: did you figure out what the issue was? You can always try running the command in terminal rather than in the notebook.

**Comment by cam1flag** [comment]
No problem :) yes I realized I can do this and the cell is killed becaue of the large data. I am figuring out how to work on a subsample of the adata.
Thanks

**Comment by cam1flag** [comment]
I know that I can take a subsample of the data using this line
adata = sc.pp.subsample(adata, fraction=None, n_obs=5000, random_state=0, copy=True)
 
But not sure where exactly to add it to the script

**Comment by Yanay1** [comment]
It might be best to subsample the anndatas in another script or notebook first, then save the subsampled versions to new files and modify the run csv to load the subsampled versions instead of the full versions.

**Comment by cam1flag** [comment]
Thanks! would it be okay to use the corresponding protein embeddings as they are? becaue I did not generate any data. 
I downloaded everything and now I have a subsampled version of the anndata but the protein embeddings not changed

**Comment by cam1flag** [comment]
Thanks! Given the fact that I did not generate any of the data and just downloaded everything, I think I should do corresponding subsampling to the protein embeddings files, no? If yes, I am not sure how to do it
Currently I am getting this error if only subsample the anndata

Global seed set to 0
Intel(R) Extension for Scikit-learn* enabled ([https://github.com/intel/scikit-learn-intelex](https://github.com/intel/scikit-learn-intelex?fbclid=IwAR3v5NAYFMsQlNWOBDJ3RKrzIRktbW1bqLLGeY2JtyPTgXLwiurxFmSY3YQ))
Using Device 0
Set seed to 0
Traceback (most recent call last):
  File "/home/mohammed/SATURN/Vignettes/frog_zebrafish_embryogenesis/../../train-saturn.py", line 1056, in <module>
    trainer(args)
  File "/home/mohammed/SATURN/Vignettes/frog_zebrafish_embryogenesis/../../train-saturn.py", line 408, in trainer
    species_to_adata = {species:sc.read(path) for species,path in species_to_path.items()}
  File "/home/mohammed/SATURN/Vignettes/frog_zebrafish_embryogenesis/../../train-saturn.py", line 408, in <dictcomp>
    species_to_adata = {species:sc.read(path) for species,path in species_to_path.items()}
  File "/home/mohammed/anaconda3/envs/saturn10/lib/python3.10/site-packages/scanpy/readwrite.py", line 112, in read
    return _read(
  File "/home/mohammed/anaconda3/envs/saturn10/lib/python3.10/site-packages/scanpy/readwrite.py", line 722, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/mohammed/anaconda3/envs/saturn10/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 238, in read_h5ad
    d[k] = read_elem(f[k])
  File "/home/mohammed/anaconda3/envs/saturn10/lib/python3.10/site-packages/anndata/_io/specs/registry.py", line 183, in read_elem
    return _REGISTRY.get_reader(type(elem), get_spec(elem), frozenset(modifiers))(elem)
  File "/home/mohammed/anaconda3/envs/saturn10/lib/python3.10/site-packages/anndata/_io/specs/methods.py", line 314, in read_array
    return elem[()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mohammed/anaconda3/envs/saturn10/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 768, in _getitem_
    return self._fast_reader.read(args)
  File "h5py/_selector.pyx", line 376, in h5py._selector.Reader.read
OSError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)

**Comment by Yanay1** [comment]
I'm not sure why that problem might be happening-- it seems like an h5py problem. Maybe there was an issue saving the subsampled anndatas? You could try making them again.

**Comment by cam1flag** [comment]
Thanks for your reply! i tried several times but unfortunately I still get the same error. Do you have any clue?

**Comment by Yanay1** [comment]
What does the code you used to subsample the anndatas look like?

**Comment by MohammedZidane** [comment]
Thanks for your reply 
Here it's 
adata = sc.pp.subsample(adata, fraction=None, n_obs=5000, random_state=0, copy=True)

**Comment by Yanay1** [comment]
Maybe the solution here: https://stackoverflow.com/questions/26301346/ioerror-cant-read-data-cant-open-directory-missing-gzip-compression-filte would work? 

I think that would mean adding `import hdf5plugin` before scanpy is imported.

**Comment by cam1flag** [comment]
Thank you so much for you trials to help:)
Unfortunately, I tried several solutions but it did not work. I am sharing with you now the full script I used for subsampling and saving the subsampled files. I would appreciate it if you try it and see if it works on your machine
```jupyter-notebook
import hdf5plugin
import tables
import scanpy as sc

adata_frog = sc.read('frog.h5ad')
adata_zebrafish = sc.read('zebrafish.h5ad')

frog_subsampled = sc.pp.subsample(adata_frog, fraction=None, n_obs=5000, random_state=0, copy=True)

zebrafish_subsampled = sc.pp.subsample(adata_zebrafish, fraction=None, n_obs=5000, random_state=0, copy=True)


zebrafish_subsampled.write_h5ad(
    'zebrafish_subsampled',
    compression=hdf5plugin.FILTERS["zstd"],
    compression_opts=hdf5plugin.Zstd(clevel=5).filter_options
)


frog_subsampled.write_h5ad(
    'frog_subsampled',
    compression=hdf5plugin.FILTERS["zstd"],
    compression_opts=hdf5plugin.Zstd(clevel=5).filter_options
)
``` 
#

**Comment by Yanay1** [comment]
Can you try writing the subsampled anndatas using:

`zebrafish_subsampled.write("zebrafish_subsampled.h5ad)`

**Comment by cam1flag** [comment]
Thanks, it worked!
