### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'saturn_results/fz_centroids.pkl'

### ISSUE THREAD

**Issue by MohammedZidane** [snap-stanford/SATURN#13]
Hi,
I ran this cell 

`!python3 ../../train-saturn.py --in_data=data/frog_zebrafish_run.csv --in_label_col=cell_type --ref_label_col=cell_type --num_macrogenes=2000 --hv_genes=8000  --centroids_init_path=saturn_results/fz_centroids.pkl --score_adata --ct_map_path=data/frog_zebrafish_cell_type_map.csv --work_dir=. --device_num=0 !python3 ../../train-saturn.py --in_data=data/frog_zebrafish_run.csv --in_label_col=cell_type --ref_label_col=cell_type --num_macrogenes=2000 --hv_genes=8000  --centroids_init_path=saturn_results/fz_centroids.pkl --score_adata --ct_map_path=data/frog_zebrafish_cell_type_map.csv --work_dir=. --device_num=0 `

But getting this error

Global seed set to 0
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
Using Device 0
Set seed to 0
After loading the anndata frog View of AnnData object with n_obs × n_vars = 500 × 9538
    obs: 'clusters', 'parent_clusters', 'cell_type', 'n_genes', 'species', 'species_type_label', 'truth_labels', 'ref_labels'
    var: 'n_cells'
After loading the anndata zebrafish View of AnnData object with n_obs × n_vars = 500 × 16980
    obs: 'n_counts', 'unique_cell_id', 'cell_names', 'library_id', 'batch', 'ClusterID', 'ClusterName', 'TissueID', 'TissueName', 'TimeID', 'cluster', 'cell_type', 'n_genes', 'species', 'species_type_label', 'truth_labels', 'ref_labels'
    var: 'n_cells'

Making Centroids

Traceback (most recent call last):
  File "/home/mohammed/SATURN/Vignettes/frog_zebrafish_embryogenesis/../../train-saturn.py", line 547, in trainer
    with open(args.centroids_init_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'saturn_results/fz_centroids.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohammed/SATURN/Vignettes/frog_zebrafish_embryogenesis/../../train-saturn.py", line 1059, in <module>
    trainer(args)
  File "/home/mohammed/SATURN/Vignettes/frog_zebrafish_embryogenesis/../../train-saturn.py", line 555, in trainer
    with open(args.centroids_init_path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'saturn_results/fz_centroids.pkl'

Could you help?
Thanks

**Comment by Yanay1** [comment]
Make sure that there exists a directory called saturn_results in the location that the script is looking for- it might be best to use an absolute path also.

**Comment by MohammedZidane** [comment]
Thanks
