### ISSUE TITLE
question about the zebrafish genome version

### ISSUE THREAD

**Issue by huawen-poppy** [snap-stanford/SATURN#17]
Hi there! I noticed that you used the GRCz11 genome for the zebrafish. Why did you choose this version? Because I checked the source paper of the zebrafish dataset, they used the GRCz10 genome.

**Comment by Yanay1** [comment]
We chose the most up to data proteomes from https://useast.ensembl.org/index.html

**Comment by huawen-poppy** [comment]
since in GRCz11, there might be newly discovered genes, and gene annotation updates, which may lead to gene symbols and identifiers could have changed, differences in gene symbols or naming schemes for the same genes, would it be a problem for the downstream analysis?

**Comment by Yanay1** [comment]
I think it is important to be aware of, and it could potentially cause future inconsistencies with a small number of gene names. However, it is computationally expensive to generate different proteome embedding files for different versions and I think the trade off is more in favor of using the most up to date, most accurate proteome.

**Comment by huawen-poppy** [comment]
I see. Thanks!
