### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tristanic** [snap-stanford/SATURN#18]
Hi! I'm interested in playing with what seems to be a really cool new tool, but noticed you don't currently seem to have a license applied to your project. According to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license, this technically means that legally nobody is allowed to do much with your code other than read it. Would you consider adding an explicit license to the repo to make your intentions clear?

**Comment by Yanay1** [comment]
Sorry about that! Added MIT license.

**Comment by tristanic** [comment]
Awesome, thank you! Looking forward to giving it a proper workout!
