### ISSUE TITLE
For which purpose is use_batch_labels used for?

### ISSUE THREAD

**Issue by cam1flag** [snap-stanford/SATURN#20]
Hi,
I see in the code (e.g. get_all_embeddings_metric in train-saturn.py) there is this parameter use_batch_labels.
It is described as 'if we add batch labels as a categorical covariate' 
I do not get the difference if I assign it to True or False. Could you calrify?

Thanks :)

**Comment by Yanay1** [comment]
`use_batch_labels` pairs with the argument `non_species_batch_col`. If you want to add an additional column from each dataset as a categorical covariate during pretraining of the autoencoder, you can pass the column name as that argument.
