### ISSUE TITLE
Are the species inputs fed to the model together?

### ISSUE THREAD

**Issue by MohammedZidane** [snap-stanford/SATURN#21]
Hi :)
I have a confusion between the figure that illustrates the model and the code. The figure shows that the model input is the genes from multiple species fed simultaneously to the model. However, what I got from the code is that each species's genes are fed individually to the model one by one.

Could you clarify this point?
Thanks!

**Comment by Yanay1** [comment]
Hi,

An individual cell will only have genes from its species. The insight from SATURN / Figure 1 is that while this is true, we can map different species genes to a shared feature space, the space of macrogenes. Thus, for cells from different species, although they have different genes, they can have the same set of features. Does that help explain?

**Comment by MohammedZidane** [comment]
yes, thanks :)
