### ISSUE TITLE
.append() does not exist anymore in pandas

### ISSUE THREAD

**Issue by anaellle** [snap-stanford/SATURN#22]
Hello, 

I am using SATURN to integrate cross-species scRNA-Seq data. I am able to run `train-saturn.py` and it seems to be doing well until I get this error : 

"../../train-saturn.py", line 820, in trainer
scores_df = scores_df.append(mmd_row, ignore_index=True)
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

I have pandas version '2.0.1' and apparently `df.append()` is not available anymore after pandas '1.4'.
Would that be possible to specify which version of pandas you are using ?

Otherwise I would suggest to use `pd.concat()` which is the alternative proposed by pandas (this is what I am currently trying to do).

Thank you !
Anaëlle

**Comment by Yanay1** [comment]
Hi, thanks for pointing out this issue!

You should be able to replace that line with:
```scores_df = pd.concat((scores_df, pd.DataFrame([mmd_row])), ignore_index=True)```

Please let me know if that works!

**Comment by anaellle** [comment]
Hi, yes it worked ! Thank you for your help. This issue is at lines 818, 820 and 847.
I take this opportunity to tell you as well that so far I found SATURN easy to use. The only thing I could suggest would be to specify that the `var_names` of the adata objects should be the gene names in the `README` file. Otherwise it is really clear.
Thank you again !

**Comment by Yanay1** [comment]
Glad to hear that, thanks for the feedback!

**Comment by cchd0001** [comment]
> Hi, yes it worked ! Thank you for your help. This issue is at lines 818, 820 and 847. I take this opportunity to tell you as well that so far I found SATURN easy to use. The only thing I could suggest would be to specify that the `var_names` of the adata objects should be the gene names in the `README` file. Otherwise it is really clear. Thank you again !


Meet the same issue, thanks

**Comment by matejasoretic** [comment]
Hi, I had the same issue and replaced the lines 818, 820 and 847, but I am still getting an issue

```
 line 818, in trainer
    scores_df = pd.concat((scores_df, pd.DataFrame([mmd_row])), ignore_index=True)
UnboundLocalError: local variable 'mmd_row' referenced before assignment

```

Edited:
Sorry, I was just silly, I see that the replacement is not exactly the same for each of the three row, but rather

 scores_df = pd.concat((scores_df, pd.DataFrame([lr_row])), ignore_index=True)
 scores_df = pd.concat((scores_df, pd.DataFrame([mmd_row])), ignore_index=True)
 scores_df = pd.concat((scores_df, pd.DataFrame([lr_cross_row])), ignore_index=True)

**Comment by dariotommasini** [comment]
Hi. Can train_saturn.py be updated with these changed?
