### ISSUE TITLE
where in the code the weights from the genes layer to the macrogenes layer are frozen?

### ISSUE THREAD

**Issue by MohammedZidane** [snap-stanford/SATURN#23]
Hi,
I could not find where the weights from the genes layer to the macrogenes layer are frozen during the training phase. Could you help?

Thanks:)

**Comment by Yanay1** [comment]
Hi,

We don't directly freeze the layer, instead, we pre-calculate the Macrogene values, and then recreate the dataloader.

https://github.com/snap-stanford/SATURN/blob/e74bd17fca3467d56de813fcd1efcf2a3660db0e/train-saturn.py#L718

Hope that makes sense!
