### ISSUE TITLE
Where is the extract.py file used in protein embedding?

### ISSUE THREAD

**Issue by vinettey** [snap-stanford/SATURN#27]
Hi! I was trying to following the Generate Protein Embeddings.ipynb tutorial but I couldn't find the extract.py file at the step of Run ESM. Where is this file located in the repo? Thank you!

**Comment by Yanay1** [comment]
It's in a specific commit to the ESM repo (not the latest version):

https://github.com/facebookresearch/esm/tree/839c5b82c6cd9e18baa7a88dcbed3bd4b6d48e47 

https://github.com/facebookresearch/esm/tree/839c5b82c6cd9e18baa7a88dcbed3bd4b6d48e47/scripts

**Comment by bitcometz** [comment]
thanks ！！！
