### ISSUE TITLE
Trouble creating protein embeddings

### ISSUE THREAD

**Issue by otoky** [snap-stanford/SATURN#30]
I am having some trouble creating the protein embeddings, namely the ensembl links are not working and also having trouble getting the esm working. 
Is there any way for you all to upload zebrafish, mouse and human embeddings, so i can skip this step?

Thanks,
Kevin

**Comment by Yanay1** [comment]
You can download precomputed ESM2 embeddings from here: https://drive.google.com/drive/folders/1_Dz7HS5N3GoOAG6MdhsXWY1nwLoN13DJ

And ESM2/ESM1b/ProtXL ones here: http://snap.stanford.edu/saturn/data/protein_embeddings.tar.gz
