### ISSUE TITLE
creation of celltype_map csv

### ISSUE THREAD

**Issue by otoky** [snap-stanford/SATURN#32]
I have two single cell datasets from two species that are labeled with cell types. However its not clear what cells = the cells in the other species, is there a way to not have connections between the species in this file?

**Comment by Yanay1** [comment]
SATURN does not use cross-species supervision. The cell type names for the species are not shared during training, so this shouldn't be an issue!

**Comment by otoky** [comment]
sounds good, theres no reason why that the NANs are sorted in the example then?
<img width="460" alt="Screenshot 2024-02-26 at 6 05 49 PM" src="https://github.com/snap-stanford/SATURN/assets/79118655/dbea3ef5-aaae-4baf-86a4-e837ac5f051c">

**Comment by Yanay1** [comment]
That file is only for scoring alignments (in which case you do need to know the matching between species).

**Comment by otoky** [comment]
is there a way to run without inputting this file? i get an error when i leave the ct_map_path blank

**Comment by Yanay1** [comment]
Yes, just remove these arguments:

```
--score_adata --ct_map_path=...
```
