### ISSUE TITLE
Error with installation？

### ISSUE THREAD

**Issue by bitcometz** [snap-stanford/SATURN#35]
hi，
I followed your installation instructions on Google Colab platform, but encountered an error. Could you please help me resolve this issue? Thank you.

![image](https://github.com/snap-stanford/SATURN/assets/13601652/0475599f-82a2-4614-aa4b-a2915a839ea4)

Best

**Comment by Yanay1** [comment]
It seems this version of torch is no longer available for download. Newer versions of torch should work fine.

**Comment by bitcometz** [comment]
@Yanay1 ,
If i chose the newer version of torch , there are some errors:

![image](https://github.com/snap-stanford/SATURN/assets/13601652/c075121c-fc2c-4719-9d33-531705c057dc)

Could you help with this problem ?

Thanks !!!

**Comment by bitcometz** [comment]
this version works ：
!pip install torch==2.2.1 -f https://download.pytorch.org/whl/cu113/torch_stable.html > 2.log
