### ISSUE TITLE
Error at the biginning of the training step : centroid_weights.append(torch.tensor(species_genes_scores[sgn])) 

### ISSUE THREAD

**Issue by Hweeseon** [snap-stanford/SATURN#36]
Hi! Thank you for your nice tool.
I am tryting to trasfer public mouse data's cell annotation to human data. 
However while the last step of training there happen to be an issue.

![saturn error](https://github.com/snap-stanford/SATURN/assets/113998108/1623adc3-df14-4083-9578-d9197d20b6af)

I can't figure out how to solve this situation. 

Could you give any advices for this circumstances? 

Thank you in advance

**Comment by Yanay1** [comment]
Hello!

You need to generate centroids for this dataset rather than using the frog and zebrafish centroids. You can change the centroids init path argument to something else and it will create a new file there.

**Comment by Hweeseon** [comment]
![image](https://github.com/snap-stanford/SATURN/assets/113998108/135376f3-d06a-427a-8b50-72ccb85caec9)

I solved the inital problem then another issue appeared. 

my adata.X dataframes are 
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

format. What should I change?

**Comment by Hweeseon** [comment]
I solved the error by reffering to previous answer. 
changing the codes in the script by, 
`scores_df = pd.concat((scores_df, pd.DataFrame([mmd_row])), ignore_index=True)`

Thank you
