### ISSUE TITLE
Help with file "zebrafish_cell_types_mapping"

### ISSUE THREAD

**Issue by bitcometz** [snap-stanford/SATURN#37]
hi,
Thanks for this great tool ！！！

I cannot find the file "zebrafish_cell_types_mapping" in the toturial:

![image](https://github.com/snap-stanford/SATURN/assets/13601652/87fb38b1-e5f2-41fc-b70e-9cc1fa5fb99f)

https://github.com/snap-stanford/SATURN/blob/main/Vignettes/frog_zebrafish_embryogenesis/dataloader.ipynb

Could you help with this problem ?

Thanks !!!

**Comment by Yanay1** [comment]
https://github.com/snap-stanford/SATURN/blob/main/Vignettes/frog_zebrafish_embryogenesis/data/zebrafish_cell_types_mapping

**Comment by bitcometz** [comment]
thanks
