### ISSUE TITLE
Which ESM2 transformer should be used for proteome-wide embedding generation?

### ISSUE THREAD

**Issue by matejasoretic** [snap-stanford/SATURN#39]
Thank you for creating this interesting tool.
In the tutorial you show how to utilise the ESM-1b transformer.
In some of the other issues you have mentioned and provided links to  ESM2 embeddings (e.g. https://github.com/snap-stanford/SATURN/issues/30)
Which ESM2 transformer should be used to generate ESM2 embeddings from a proteome?

**Comment by Yanay1** [comment]
ESM2 15B
