### ISSUE TITLE
KeyError: 'cell_type'

### ISSUE THREAD

**Issue by houruiyan** [snap-stanford/SATURN#4]
Hi,  Dr , I meet another question. 
```
Using Device 0
Set seed to 0
Traceback (most recent call last):
  File "/home/houruiyan/.conda/envs/run_saturn/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'cell_type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/houruiyan/software/saturn/train-saturn.py", line 1056, in <module>
    trainer(args)
  File "/data/users/houruiyan/software/saturn/train-saturn.py", line 438, in trainer
    species_str.index = adata.obs[adata_label].index
  File "/home/houruiyan/.conda/envs/run_saturn/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/houruiyan/.conda/envs/run_saturn/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'cell_type'
```
It seesms that I did not include the "cell_type" keywords. But I do not know where should I include this keyword. 

My cell type mapping file look like this. 
![image](https://user-images.githubusercontent.com/56068158/222952808-3f7535bf-8c65-43d0-9078-c12fba4623f4.png)

My path matrix look like this. 
![image](https://user-images.githubusercontent.com/56068158/222952835-046f7222-8f6c-4e9d-ae3c-a07023f2444a.png)

My code look like this.

```
python /data/users/houruiyan/software/saturn/train-saturn.py \
--in_data /data/users/houruiyan/run_saturn/path_matrix.csv \
--in_label_col=cell_type --ref_label_col=cell_type \
--num_macrogenes=2000     --hv_genes=8000 \
--centroids_init_path=/data/users/houruiyan/run_saturn//four_centroids.pkl \
--score_adata --ct_map_path=/data/users/houruiyan/run_saturn/cellType_info.csv \
--work_dir=. \
--device_num=0

```

Could you help me,  Thank you!

**Comment by Yanay1** [comment]
What columns do your h5ad files have in the obs slot? The error might be because they’re missing a column called cell_type.

**Comment by houruiyan** [comment]
Hello , 

I correct the cluster_type to cell_type. But here is a new problem. 

```
  File "/data/users/houruiyan/software/saturn/train-saturn.py", line 108
    key = f"{indices_mapped[0][j]},{indices_mapped[1][j]},{indices_mapped[2][j]}"
                                                                                ^
SyntaxError: invalid syntax
```
Is there method to fix this bug?

**Comment by Yanay1** [comment]
What version of python are you using? Please use 3.8 or later.

**Comment by houruiyan** [comment]
Hello Dr ,

I update the python. But now I got a new problem.

```
Traceback (most recent call last):
  File "/data/users/houruiyan/software/saturn/train-saturn.py", line 17, in <module>
    import scanpy as sc
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/__init__.py", line 14, in <module>
    from . import tools as tl
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/tools/__init__.py", line 1, in <module>
    from ..preprocessing import pca
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/preprocessing/__init__.py", line 1, in <module>
    from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/preprocessing/_recipes.py", line 8, in <module>
    from ._deprecated.highly_variable_genes import (
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/preprocessing/_deprecated/highly_variable_genes.py", line 11, in <module>
    from .._utils import _get_mean_var
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/preprocessing/_utils.py", line 46, in <module>
    def sparse_mean_var_minor_axis(data, indices, major_len, minor_len, dtype):
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/numba/core/decorators.py", line 212, in wrapper
    disp.enable_caching()
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/numba/core/dispatcher.py", line 863, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/numba/core/caching.py", line 601, in __init__
    self._impl = self._impl_class(py_func)
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/numba/core/caching.py", line 337, in __init__
    raise RuntimeError("cannot cache function %r: no locator available "
RuntimeError: cannot cache function 'sparse_mean_var_minor_axis': no locator available for file '/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/preprocessing/_utils.py'
```

Could you help me? Thank you

**Comment by Yanay1** [comment]
This appears to be an issue with your versions of scanpy and numba:

The versions of scanpy and numba we have are:

```
scanpy                      1.9.1
numba                       0.56.0
```
So you could try uninstalling scanpy and numba and then installing these. If that doesn't work, it might help also asking on the scanpy github issues.

**Comment by houruiyan** [comment]
Thank you very much! 

But there is a new problem. 

```
Traceback (most recent call last):
  File "/data/users/houruiyan/software/saturn/train-saturn.py", line 17, in <module>
    import scanpy as sc
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/__init__.py", line 16, in <module>
    from . import plotting as pl
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/scanpy/plotting/_utils.py", line 35, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```
Very sorry for my multiple question. Thank you very much!

**Comment by Yanay1** [comment]
No worries! Try using the following version of the anndata package:

```anndata                     0.8.0```

If there are still import issues after, could you please paste the results of the command `pip list`?

**Comment by houruiyan** [comment]
Thank you.

I think this is not the anndata problem 

```
(Py3) pip install anndata==0.8.0
Requirement already satisfied: anndata==0.8.0 in /home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages (0.8.0)
Requirement already satisfied: natsort in /home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages (from anndata==0.8.0) (8.3.1)
Requirement already satisfied: packaging>=20 in /home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages (from anndata==0.8.0) (23.0)
Requirement already satisfied: scipy>1.4 in /home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages (from anndata==0.8.0) (1.10.1)
Requirement already satisfied: numpy>=1.16.5 in /home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages (from anndata==0.8.0) (1.22.3)
Requirement already satisfied: pandas>=1.1.1 in /home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages (from anndata==0.8.0) (1.5.3)
Requirement already satisfied: h5py>=3 in /home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages (from anndata==0.8.0) (3.8.0)
Requirement already satisfied: pytz>=2020.1 in /home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages (from pandas>=1.1.1->anndata==0.8.0) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages (from pandas>=1.1.1->anndata==0.8.0) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas>=1.1.1->anndata==0.8.0) (1.16.0)

```

It is already the 0.8.0

This is the result of pip list

```
Package                  Version
------------------------ ------------
absl-py                  1.4.0
aiohttp                  3.8.4
aiosignal                1.3.1
anndata                  0.8.0
anyio                    3.6.2
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
async-timeout            4.0.2
attrs                    22.2.0
backcall                 0.2.0
beautifulsoup4           4.11.2
biopython                1.81
bleach                   6.0.0
brotlipy                 0.7.0
cached-property          1.5.2
certifi                  2022.12.7
cffi                     1.15.1
charset-normalizer       2.0.4
chex                     0.1.6
comm                     0.1.2
contextlib2              21.6.0
contourpy                1.0.7
cryptography             39.0.1
cycler                   0.11.0
daal                     2023.0.1
daal4py                  2023.0.1
debugpy                  1.6.6
decorator                5.1.1
defusedxml               0.7.1
dm-tree                  0.1.8
docrep                   0.3.2
ensembl-rest             0.3.3
et-xmlfile               1.1.0
etils                    1.0.0
executing                1.2.0
fair-esm                 2.0.0
faiss-gpu                1.7.2
fastjsonschema           2.16.3
flax                     0.6.6
flit_core                3.6.0
fonttools                4.38.0
fqdn                     1.5.1
frozenlist               1.3.3
fsspec                   2023.3.0
h5py                     3.8.0
idna                     3.4
igraph                   0.10.4
importlib-metadata       6.0.0
importlib-resources      5.12.0
intervaltree             3.1.0
ipdb                     0.13.11
ipykernel                6.21.2
ipython                  8.11.0
ipython-genutils         0.2.0
isoduration              20.11.0
jax                      0.4.5
jaxlib                   0.4.4
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.2.0
jsonpointer              2.3
jsonschema               4.17.3
jupyter_client           8.0.3
jupyter_core             5.2.0
jupyter-events           0.6.3
jupyter_server           2.3.0
jupyter_server_terminals 0.4.4
jupyterlab-pygments      0.2.2
kiwisolver               1.4.4
lightning-utilities      0.7.1
llvmlite                 0.39.1
louvain                  0.8.0
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib               3.7.1
matplotlib-inline        0.1.6
mdurl                    0.1.2
mistune                  2.0.5
ml-collections           0.1.1
msgpack                  1.0.4
mudata                   0.2.1
multidict                6.0.4
multipledispatch         0.6.0
mypy-extensions          1.0.0
natsort                  8.3.1
nbclassic                0.5.2
nbclient                 0.7.2
nbconvert                7.2.9
nbformat                 5.7.3
nest-asyncio             1.5.6
networkx                 3.0
notebook                 6.5.2
notebook_shim            0.2.2
numba                    0.56.0
numpy                    1.22.3
numpyro                  0.11.0
openpyxl                 3.1.1
opt-einsum               3.3.0
optax                    0.1.4
orbax                    0.1.3
packaging                23.0
pandas                   1.5.3
pandocfilters            1.5.0
parso                    0.8.3
patsy                    0.5.3
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.4.0
pip                      22.3.1
pkgutil_resolve_name     1.3.10
platformdirs             3.1.0
plotly                   5.13.1
prometheus-client        0.16.0
prompt-toolkit           3.0.38
psutil                   5.9.4
ptyprocess               0.7.0
pure-eval                0.2.2
pycparser                2.21
Pygments                 2.14.0
pynndescent              0.5.8
pyOpenSSL                23.0.0
pyparsing                3.0.9
pyro-api                 0.1.2
pyro-ppl                 1.8.4
pyrsistent               0.19.3
PySocks                  1.7.1
python-dateutil          2.8.2
python-json-logger       2.0.7
pytorch-lightning        1.9.4
pytz                     2022.7.1
PyYAML                   6.0
pyzmq                    25.0.0
record-keeper            0.9.32
requests                 2.28.1
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rich                     13.3.2
scanpy                   1.9.1
scikit-learn             1.2.1
scikit-learn-intelex     2023.0.1
scikit-misc              0.1.4
scipy                    1.10.1
scvi-tools               0.20.1
seaborn                  0.12.2
Send2Trash               1.8.0
session-info             1.0.0
setuptools               65.6.3
simplejson               3.18.3
six                      1.16.0
sniffio                  1.3.0
sortedcontainers         2.4.0
soupsieve                2.4
stack-data               0.6.2
statsmodels              0.13.5
stdlib-list              0.8.0
tbb                      2021.8.0
tenacity                 8.2.2
tensorstore              0.1.33
terminado                0.17.1
texttable                1.6.7
threadpoolctl            3.1.0
tinycss2                 1.2.1
tomli                    2.0.1
toolz                    0.12.0
torch                    1.10.2+cu113
torchaudio               0.13.1
torchmetrics             0.11.3
torchvision              0.14.1
tornado                  6.2
tqdm                     4.65.0
traitlets                5.9.0
typed-argument-parser    1.7.2
typing_extensions        4.4.0
typing-inspect           0.8.0
umap-learn               0.5.3
uri-template             1.2.0
urllib3                  1.26.14
wcwidth                  0.2.6
webcolors                1.12
webencodings             0.5.1
websocket-client         1.5.1
wheel                    0.38.4
yarl                     1.8.2
zipp                     3.15.0

```

**Comment by Yanay1** [comment]
Per https://github.com/scverse/scanpy/issues/2411 please try downgrading matplotlib to a version less than 3.7.0, for example 3.5.3.

**Comment by houruiyan** [comment]
Hello, Dr 

Last time, you suggest me to install pytorch locally. Is this ok? 

`conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia`

Because I meet this question again

```
Global seed set to 0
Traceback (most recent call last):
  File "/data/users/houruiyan/software/saturn/train-saturn.py", line 36, in <module>
    from pretrain_utils import *
  File "/data/users/houruiyan/software/saturn/pretrain_utils.py", line 9, in <module>
    from utils.transformations import *
  File "/data/users/houruiyan/software/saturn/utils/transformations.py", line 4, in <module>
    import torchvision.datasets as datasets
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/torchvision/models/__init__.py", line 17, in <module>
    from . import detection, optical_flow, quantization, segmentation, video
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/torchvision/models/quantization/__init__.py", line 3, in <module>
    from .mobilenet import *
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import *  # noqa: F401, F403
  File "/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py", line 5, in <module>
    from torch.ao.quantization import DeQuantStub, QuantStub
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' (/home/houruiyan/micromamba/envs/Py3.8/lib/python3.8/site-packages/torch/ao/quantization/__init__.py)
(Py3)
```

**Comment by Yanay1** [comment]
Could you clarify what you mean by locally? You would have to instal torch in the conda environment as well.

**Comment by houruiyan** [comment]
I install pytorch by using this code 

 `conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia`

Then I found it produce other error. I do not record it.  But I think it may be due to the version proble. So I reinstall by your code .

`pip install torch==1.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`

Now it produce the problem mentioned above. 
`ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization'
`
Now I want to reinstall pytorch by conda. I found that it shows it already installed. 
So I do not how to do. 

Next I try to use pip to install the package here.

```
torch                       1.12.1+cu113

torch-cluster               1.6.0

torch-geometric             2.1.0.post1

torch-scatter               2.0.9

torch-sparse                0.6.15

torch-spline-conv           1.2.1

torchaudio                  0.12.1+cu113

torchmetrics                0.9.3
```

I found most of them cannot install successfully. such as torch-sparse ,torch-geometric ,torchaudio 

Thank you!

**Comment by houruiyan** [comment]
Dear Dr, 

I solved the pytorch version problem. But there is a new problem. 

```
Traceback (most recent call last):
  File "/data/users/houruiyan/software/saturn/train-saturn.py", line 1056, in <module>
    trainer(args)
  File "/data/users/houruiyan/software/saturn/train-saturn.py", line 501, in trainer
    adata, species_gene_embeddings = load_gene_embeddings_adata(
  File "/data/users/houruiyan/software/saturn/data/gene_embeddings.py", line 114, in load_gene_embeddings_adata
    species_to_gene_embeddings = {
  File "/data/users/houruiyan/software/saturn/data/gene_embeddings.py", line 115, in <dictcomp>
    species_name: torch.stack([
RuntimeError: stack expects a non-empty TensorList
```

Could you help me? Thank you!

**Comment by Yanay1** [comment]
This usually happens because there is a mismatch between the gene names in your anndata files and the gene names in the protein embeddings. Double check that there are genes in common between each species' anndata and the corresponding protein embedding file.

**Comment by houruiyan** [comment]
Thank you very much for your reply! 

Actually, I found there are a lot of genes which are common between anndata and corresponding protein embedding file.

These are some content of jason file
![image](https://user-images.githubusercontent.com/56068158/223307515-49a353d9-50b5-46de-b325-28027e07ecd4.png)





This is my anndata
![image](https://user-images.githubusercontent.com/56068158/223307325-092d1e3b-4f2c-4ed6-be23-87710c4c0449.png)

Could you help me? Thank you!

**Comment by Yanay1** [comment]
Could you double check that that is the case for all the species you are aligning?

**Comment by houruiyan** [comment]
Yes, I check all the four species. They are all contains genes which is consistent between json file and anndata file. 
![image](https://user-images.githubusercontent.com/56068158/224527821-7d4490e9-b119-4861-89ff-c8c12e216c93.png)
Can you help me? Thank you!

**Comment by Yanay1** [comment]
What is the output of SATURN before the error occurs?

**Comment by houruiyan** [comment]
Thank you for your quick reply! 
It did not have any other error occursing?  The result  is as following.
![image](https://user-images.githubusercontent.com/56068158/224528998-f3a4e7b4-66bc-49c6-bdc9-5a17461ea16b.png)

**Comment by Yanay1** [comment]
What do your protein embedding files look like for each species?

**Comment by houruiyan** [comment]
I am sorry. I do not know how to check the embedding files. It is a binary file. 
![image](https://user-images.githubusercontent.com/56068158/224531339-c10652b4-60f8-4f88-8413-e4842ebb6964.png)

**Comment by Yanay1** [comment]
You can view them in Python using `torch.load(…)`

**Comment by houruiyan** [comment]
Dear Dr , thank you for your reply. according to your instruction. I found my human embedding file is empt. Then I fix it. 
But now, a new error appears. 

![image](https://user-images.githubusercontent.com/56068158/224537109-c28dc867-bc87-4e69-bd0a-e4e6a71785fb.png)
Could you help me? Thank you!

**Comment by Yanay1** [comment]
Did you set any arguments to “cells”?

**Comment by houruiyan** [comment]
No, I did not. 

```
#!/bin/bash

python /data/users/houruiyan/software/saturn/train-saturn.py \
--in_data /data/users/houruiyan/run_saturn/path_matrix.csv \
--in_label_col=cell_type --ref_label_col=cell_type \
--num_macrogenes=2000     --hv_genes=8000 \
--centroids_init_path=/data/users/houruiyan/run_saturn//four_centroids.pkl \
--score_adata --ct_map_path=/data/users/houruiyan/run_saturn/cellType_info.csv \
--work_dir=. \
--device_num=0
```

This is my code.

**Comment by Yanay1** [comment]
Try replacing all the underscores with spaces in the cell type mapping file.

**Comment by houruiyan** [comment]
Yes，thank you for your reply. I replace all the underscoreds with spaces. 
My cell type mapping file looks like this. 
![image](https://user-images.githubusercontent.com/56068158/224666739-6f58bd4e-271b-457b-867b-ca0f4039c336.png)
But I got this error. 
![image](https://user-images.githubusercontent.com/56068158/224666839-b1aee9ce-d3a0-41ee-a18f-7b2513d14e47.png)
Hope to get your reply. Thank you very much!

**Comment by Yanay1** [comment]
Sorry, remove the underscores from the row values, not the names of the columns.

**Comment by houruiyan** [comment]
Dear Dr, 

I found  the method mentioned above cannot work. It has this error. 
![image](https://user-images.githubusercontent.com/56068158/224872063-11265b43-4c08-439d-8e2b-4a5326c8d1d1.png)

This is my cell type map information. 

![image](https://user-images.githubusercontent.com/56068158/224872155-88fcc165-b86c-4b07-80af-4628654dabe8.png)

**Comment by Yanay1** [comment]
Make sure the cell types in the AnnDatas match the cell types in this file (no underscores). You should run SATURN without scoring at least once just so it completes so that it can complete training and then you can try scoring the final result.

**Comment by houruiyan** [comment]
Thank you very much!　I get the final result. Thank you !
Your suggestion fix my problem.

**Comment by matejasoretic** [comment]
Hello, I am having a similar error to the very first error reported in this thread, with the KeyError cell_type
I have double checked, and made sure all of my h5ad objects have a .obs.cell_type column, and they do, but I still get the KeyError: 'cell_type'

`
Using Device 0
Set seed to 0
Traceback (most recent call last):
  File "/path/to/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'cell_type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/train-saturn.py", line 1064, in <module>
    trainer(args)
  File "/path/to/train-saturn.py", line 441, in trainer
    species_str.index = adata.obs[adata_label].index
  File "/path/to/frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/path/to/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'cell_type'
`
My command was:
`python3 /path/to/train-saturn.py \
--in_data=/path/to/all_species_run.csv \
--in_label_col=cell_type --ref_label_col=cell_type \
--num_macrogenes=2000 --hv_genes=8000 \
--centroids_init_path=/path/to/saturn_results//all_species_centroids.pkl \
--score_adata --ct_map_path=/path/to/cell_type_map.csv \
--work_dir=/path/to/work_dir `

Is there something else that could be causing this error?

**Comment by ThomasGTHB** [comment]
Hi sir,

I am raising this issue again, since there seems to be an unintended behavior in the handling of cell type names. As you mentioned earlier, there should be no underscores _ in the cell type names. This is due to the command at line 391 in the file train-saturn.py
adata.obs['labels2'] = pd.Categorical([l.split('_')[-1] for l in adata.obs['labels']])
As you append the species name as "species_cellType" earlier, you have to proceed this way to separate the cell type later.

However, in several data files that I have been using, the cell types are stored using underscores _. The problem is that Python will still do the split without raising an error, and lose the first part of the name. In some cases, it has even been using previously stored values of the cell types from another run, when the resulting cell types did not match the ct_map_path csv file. The file train-saturn.py runs normally, no error is raised, but at the end the species are not integrated correctly, and some of the cell types in the plots do not match those in the input data. Everything works fine when I remove all underscores.

To reproduce the issue, you can add underscores in some of your cell types (both in the adata object and in the ct_map_path csv file).

Could you maybe put a warning in the section "Scoring SATURN outputs" about that? (Let me know if the error comes from my part.)

Best
