### ISSUE TITLE
Within species integration

### ISSUE THREAD

**Issue by cadyyuheng** [snap-stanford/SATURN#40]
I was trying to apply Saturn for mouse and human dataset integration. However, for either human or mouse individual species, our datasets are from multiple animals, experiments, and  SC technologies (the same tissue). I wonder for this case, what would be the recommended practice for analysis. Do we need to conduct any pre-processing to remove batch effects within the same species? Or can we simply cluster each individual dataset, aggregate datasets into one species-specific one with dataset-specific cluster label, and then use Saturn to integrate across two species? 

Thanks!

**Comment by Yanay1** [comment]
I think this option:
```
Or can we simply cluster each individual dataset, aggregate datasets into one species-specific one with dataset-specific cluster label, and then use Saturn to integrate across two species?
```
Is probably the simplest solution.
