### ISSUE TITLE
Question: protein embedding, are we only using protein sequences?

### ISSUE THREAD

**Issue by YaoLi3** [snap-stanford/SATURN#50]
Hello,

Thanks again for the awesome framework!

I have a question about protein embedding, are we using amino acid sequences to generate protein embeddings, or we firstly use sequences to predict protein structures then create protein embeddings? 

Thanks in advance,
Yao

**Comment by Yanay1** [comment]
We use a protein language model (like ESM2) to generate embeddings. It takes amino acid sequences as an input and produces an embedding. It does not take in structure as an input, however, it can be used to predict structures.

**Comment by YaoLi3** [comment]
Thanks a lot for your swift reply!
