### ISSUE TITLE
Looking for "publicly available protein embedding datasets we have provided."

### ISSUE THREAD

**Issue by vishnums007** [snap-stanford/SATURN#52]
Hi, 
I am looking for these embedding datasets for zebrafish, mouse and humans?

'Homo_sapiens.GRCh38.gene_symbol_to_embedding_ESM2.pt',
'Mus_musculus.GRCm39.gene_symbol_to_embedding_ESM2.pt',
'Danio_rerio.GRCz11.gene_symbol_to_embedding_ESM2.pt'

Where can I find these? Could you please help me?

**Comment by Yanay1** [comment]
http://snap.stanford.edu/saturn/data/protein_embeddings.tar.gz

**Comment by vishnums007** [comment]
Thank you!

**Comment by wangqiuba2024** [comment]
Hi, @Yanay1 
what is different between embedding datasets file.tourch and file.pt . can change format?  thanks !
