### ISSUE TITLE
Out of memory error when using ESM2 for protein embeddings

### ISSUE THREAD

**Issue by dariotommasini** [snap-stanford/SATURN#56]
Hello, 

Thank you for a great tool! I was able to generate protein embeddings using the tutorial in protein_embeddings folder, which uses ESM1b. I tried using ESM2 and I get out of memory issues. I saw the example they have in the esm2 repository to handle this: examples/esm2_infer_fairscale_fsdp_cpu_offloading.py. Is there any chance you have an example of generating the protein embeddings using this offloading feature? Or do you recommend some other solution to this e.g. distributing over multiple GPUs or using a bigger GPU?

**Comment by Yanay1** [comment]
A bigger gpu is probably the safest bet. I can also generate it for you if you let me know which species/proteome file you'd like.

**Comment by dariotommasini** [comment]
Thank you @Yanay1! That's very generous. I'll have to take you up on that offer as I tried our largest gpu and still ran into memory issues. I'll email you the protein fasta files. Thanks again!

**Comment by wangqiuba2024** [comment]
hi, @Yanay1 ,
Could you please help me create a new species Mesocricetus_auratus (golden_hamster )  ESM2 ?  Thanks a lot!

best
xin

**Comment by Yanay1** [comment]
I've uploaded the embeddings to google drive here: https://drive.google.com/drive/folders/1_Dz7HS5N3GoOAG6MdhsXWY1nwLoN13DJ

**Comment by wangqiuba2024** [comment]
hi, @Yanay1 :  I 've downloaded the embeddings  (Mesocricetus_auratus) from google . 
Is there something wrong with this ''species_name: torch.stack([
RuntimeError: stack expects a non-empty TensorList",    but other species file (such as  Drosophila_melanogaster.BDGP6.46.pep.all.gene_symbol_to_embedding_ESM2.pt) from google were not. 
Thanks again!
