### ISSUE TITLE
The meaning of weights in macrogene?

### ISSUE THREAD

**Issue by xuzhougeng** [snap-stanford/SATURN#59]
This is a very good work, and the results in my data are great.

I have some confusion about macrogene.

1. The total weights of different macrogenes are different. Does this mean that the macrogene with higher weights has a greater effect？
2. The weights of the same macrogene are different. Can they be filtered based on a threshold?

**Comment by Yanay1** [comment]
Thanks!

1. I would not interpret the macrogene weights in that manner. A high sum of weights to the macrogene could just mean there are many equally highly weighted genes to it.

2. To interpret a macrogene we looked at some number of the top genes. Usually there is a dramatic drop off in the gene weights, one example for a cutoff was not looking at genes if the weight was below 0.5. But in some cases, all genes will have weights below 0.5 and you can only look at the top 3-10 or something.

**Comment by zhuojiuqingyun** [comment]
> Thanks!
> 
> 1. I would not interpret the macrogene weights in that manner. A high sum of weights to the macrogene could just mean there are many equally highly weighted genes to it.
> 2. To interpret a macrogene we looked at some number of the top genes. Usually there is a dramatic drop off in the gene weights, one example for a cutoff was not looking at genes if the weight was below 0.5. But in some cases, all genes will have weights below 0.5 and you can only look at the top 3-10 or something.

I want to know if the following conclusion can be drawn: If a macrogene is highly expressed in a cell, are the genes with the highest weight (associated with this macrogene) also highly expressed?
