### ISSUE TITLE
Which seed is the best in your frog_zebrafish_embryogenesis analysis?

### ISSUE THREAD

**Issue by vishnums007** [snap-stanford/SATURN#60]
@Yanay1 , I have a naive question regarding the highest integration score after running multiple seeds. In you vignette, the fz_multi_seeds_scores.csv provides values for logistic and balanced regression. I am assuming the best integration seed is the one that got highest logistic and balanced regression? If that is true,  is it seed # 19 the selected seed for your frog_zebrafish_embryogenesis analysis. Seed#19 got has logistic regression = 0.867293 	 and balanced regression =0.545929 , which is the highest that you got out of 30 different seeds. 

 I have a naive question regarding the highest integration score after running multiple seeds. In you vignette, the fz_multi_seeds_scores.csv provides values for logistic and balanced regression. I am assuming the best integration seed is the one that got highest logistic and balanced regression? If that is true,  is it seed # 19 the selected seed for your frog_zebrafish_embryogenesis analysis. Seed#19 got has logistic regression = 0.867293 	 and balanced regression =0.545929 , which is the highest that you got out of 30 different seeds. 

Thanking you in advance for your time

_Originally posted by @vishnums007 in https://github.com/snap-stanford/SATURN/issues/54#issuecomment-2115585641_

**Comment by Yanay1** [comment]
https://github.com/snap-stanford/SATURN/issues/54#issuecomment-2115943012
