### ISSUE TITLE
trouble installing the package

### ISSUE THREAD

**Issue by RanZhang08** [snap-stanford/SATURN#63]
Dear authors,

I got the following error while trying to run train-saturn.py:
```
  File ".../anaconda3/envs/SATURN/lib/python3.9/site-packages/lightning/fabric/utilities/types.py", line 37, in <module>
    torch.UntypedStorage if _TORCH_GREATER_EQUAL_1_13 else torch._UntypedStorage  # type: ignore[valid-type]
AttributeError: module 'torch' has no attribute '_UntypedStorage'
```
Here is my current torch version:
```
torch                     1.10.2+cu113             pypi_0    pypi
torchmetrics              1.4.0.post0              pypi_0    pypi
torchvision               0.18.1                   pypi_0    pypi
```
Would you please advise how to fix the problem?

Thanks a lot!

**Comment by jlr13** [comment]
I have the same issue, it would be helpful if the requirements.txt file included package versions!

**Comment by jlr13** [comment]
I think I might have got it working by playing around with package versions, until there is some official fix you can try these.

<details>
<summary><code>requirements.txt</code></summary>

```
absl-py==2.1.0
aiobotocore==2.13.1
aiohttp==3.9.5
aioitertools==0.11.0
aiosignal==1.3.1
anndata==0.10.8
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.4.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array_api_compat==1.7.1
arrow==1.3.0
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.2.0
Babel==2.15.0
backoff==2.2.1
beautifulsoup4==4.12.3
biopython==1.84
bleach==6.1.0
blessed==1.20.0
boto3==1.34.131
botocore==1.34.131
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
chex==0.1.7
click==8.1.7
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1710320294760/work
contextlib2==21.6.0
contourpy==1.2.1
croniter==1.3.15
cycler==0.12.1
daal==2024.5.0
daal4py==2024.5.0
dateutils==0.6.12
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1719378673901/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
deepdiff==7.0.1
defusedxml==0.7.1
dm-tree==0.1.8
dnspython==2.6.1
docrep==0.3.2
docstring_parser==0.16
editor==1.6.6
email_validator==2.2.0
ensembl-rest==0.3.4
et-xmlfile==1.1.0
etils==1.5.2
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1704921103267/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1698579936712/work
fair-esm==2.0.0
faiss-gpu==1.7.2
fastapi==0.88.0
fastapi-cli==0.0.4
fastjsonschema==2.20.0
filelock==3.15.4
fire==0.6.0
flax==0.8.5
fonttools==4.53.0
fqdn==1.5.1
frozenlist==1.4.1
fsspec==2023.12.2
future==1.0.0
get-annotations==0.1.2
grpcio==1.64.1
h11==0.14.0
h5py==3.11.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.0
hydra-core==1.3.2
idna==3.7
igraph==0.11.5
importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1719361860083/work
importlib_resources==6.4.0
inquirer==3.3.0
intervaltree==3.1.0
ipdb==0.13.13
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1717717528849/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1701831663892/work
ipywidgets==8.1.3
isoduration==20.11.0
itsdangerous==2.2.0
jax==0.4.30
jaxlib==0.4.30
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
Jinja2==3.1.4
jmespath==1.0.1
joblib==1.4.2
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1716472197302/work
jupyter_core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1710257447442/work
jupyter_server==2.14.1
jupyter_server_terminals==0.5.3
jupyterlab==4.2.3
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.2
jupyterlab_widgets==3.0.11
kiwisolver==1.4.5
legacy-api-wrap==1.4
lightning-cloud==0.5.70
lightning-lite==1.8.6
lightning-utilities==0.11.3.post0
llvmlite==0.43.0
louvain==0.8.2
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.0
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1713250518406/work
mdurl==0.1.2
mistune==3.0.2
ml-dtypes==0.4.0
ml_collections==0.1.1
mpmath==1.3.0
msgpack==1.0.8
mudata==0.2.4
multidict==6.0.5
multipledispatch==1.0.0
mypy-extensions==1.0.0
natsort==8.4.0
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest_asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1705850609492/work
networkx==3.2.1
notebook==7.2.1
notebook_shim==0.2.4
numba==0.60.0
numpy==1.26.4
numpyro==0.15.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.5.40
nvidia-nvtx-cu12==12.1.105
omegaconf==2.3.0
openpyxl==3.1.5
opt-einsum==3.3.0
optax==0.2.1
orbax-checkpoint==0.5.20
ordered-set==4.1.0
orjson==3.10.6
overrides==7.7.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1718189413536/work
pandas==1.5.0
pandocfilters==1.5.1
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1712320355065/work
patsy==0.5.6
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1706113125309/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
pillow==10.3.0
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1715777629804/work
plotly==5.22.0
prometheus_client==0.20.0
prompt_toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1718047967974/work
protobuf==3.20.1
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1719274564771/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pycparser==2.22
pydantic==1.10.17
pydantic_core==2.4.0
pyDeprecate==0.3.0
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1714846767233/work
PyJWT==2.8.0
pynndescent==0.5.13
pyparsing==3.1.2
pyro-api==0.1.2
pyro-ppl==1.8.0
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1709299778482/work
python-dotenv==1.0.1
python-json-logger==2.0.7
python-multipart==0.0.9
pytorch-lightning==1.3.8
pytz==2024.1
PyYAML==5.4.1
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1715024408309/work
readchar==4.1.0
record-keeper==0.9.32
referencing==0.35.1
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.1
rpds-py==0.18.1
runs==1.2.2
s3fs==2023.12.2
s3transfer==0.10.2
scanpy==1.10.2
scikit-learn==1.5.0
scikit-learn-intelex==2024.5.0
scikit-misc==0.3.1
scipy==1.13.1
scvi-tools==0.14.0
seaborn==0.13.2
Send2Trash==1.8.3
session_info==1.0.0
shellingham==1.5.4
simplejson==3.19.2
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sniffio==1.3.1
sortedcontainers==2.4.0
soupsieve==2.5
sparse==0.15.4
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
starlette==0.22.0
starsessions==1.3.0
statsmodels==0.14.2
stdlib-list==0.10.0
sympy==1.12.1
tbb==2021.13.0
tenacity==8.4.2
tensorboard==2.17.0
tensorboard-data-server==0.7.2
tensorstore==0.1.63
termcolor==2.4.0
terminado==0.18.1
texttable==1.7.0
threadpoolctl==3.5.0
tinycss2==1.3.0
tomli==2.0.1
toolz==0.12.1
torch==1.10.2+cu113
torchmetrics==0.6.0
torchvision==0.11.3
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1717722887379/work
tqdm==4.66.4
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1713535121073/work
triton==2.3.1
typed-argument-parser==1.10.0
typer==0.12.3
types-python-dateutil==2.9.0.20240316
typing-inspect==0.9.0
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1717802530399/work
tzdata==2024.1
ujson==5.10.0
umap-learn==0.5.6
uri-template==1.3.0
urllib3==1.26.19
uvicorn==0.30.1
uvloop==0.19.0
watchfiles==0.22.0
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1704731205417/work
webcolors==24.6.0
webencodings==0.5.1
websocket-client==1.8.0
websockets==11.0.3
Werkzeug==3.0.3
widgetsnbextension==4.0.11
wrapt==1.16.0
xarray==2024.3.0
xmod==1.8.1
yarl==1.9.4
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1718013267051/work

```
</details>

**Comment by weiluwl** [comment]
> I think I might have got it working by playing around with package versions, until there is some official fix you can try these.
> 
> `requirements.txt`
> ```
> absl-py==2.1.0
> aiobotocore==2.13.1
> aiohttp==3.9.5
> aioitertools==0.11.0
> aiosignal==1.3.1
> anndata==0.10.8
> annotated-types==0.7.0
> antlr4-python3-runtime==4.9.3
> anyio==4.4.0
> argon2-cffi==23.1.0
> argon2-cffi-bindings==21.2.0
> array_api_compat==1.7.1
> arrow==1.3.0
> asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
> async-lru==2.0.4
> async-timeout==4.0.3
> attrs==23.2.0
> Babel==2.15.0
> backoff==2.2.1
> beautifulsoup4==4.12.3
> biopython==1.84
> bleach==6.1.0
> blessed==1.20.0
> boto3==1.34.131
> botocore==1.34.131
> certifi==2024.6.2
> cffi==1.16.0
> charset-normalizer==3.3.2
> chex==0.1.7
> click==8.1.7
> comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1710320294760/work
> contextlib2==21.6.0
> contourpy==1.2.1
> croniter==1.3.15
> cycler==0.12.1
> daal==2024.5.0
> daal4py==2024.5.0
> dateutils==0.6.12
> debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1719378673901/work
> decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
> deepdiff==7.0.1
> defusedxml==0.7.1
> dm-tree==0.1.8
> dnspython==2.6.1
> docrep==0.3.2
> docstring_parser==0.16
> editor==1.6.6
> email_validator==2.2.0
> ensembl-rest==0.3.4
> et-xmlfile==1.1.0
> etils==1.5.2
> exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1704921103267/work
> executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1698579936712/work
> fair-esm==2.0.0
> faiss-gpu==1.7.2
> fastapi==0.88.0
> fastapi-cli==0.0.4
> fastjsonschema==2.20.0
> filelock==3.15.4
> fire==0.6.0
> flax==0.8.5
> fonttools==4.53.0
> fqdn==1.5.1
> frozenlist==1.4.1
> fsspec==2023.12.2
> future==1.0.0
> get-annotations==0.1.2
> grpcio==1.64.1
> h11==0.14.0
> h5py==3.11.0
> httpcore==1.0.5
> httptools==0.6.1
> httpx==0.27.0
> hydra-core==1.3.2
> idna==3.7
> igraph==0.11.5
> importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1719361860083/work
> importlib_resources==6.4.0
> inquirer==3.3.0
> intervaltree==3.1.0
> ipdb==0.13.13
> ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1717717528849/work
> ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1701831663892/work
> ipywidgets==8.1.3
> isoduration==20.11.0
> itsdangerous==2.2.0
> jax==0.4.30
> jaxlib==0.4.30
> jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
> Jinja2==3.1.4
> jmespath==1.0.1
> joblib==1.4.2
> json5==0.9.25
> jsonpointer==3.0.0
> jsonschema==4.22.0
> jsonschema-specifications==2023.12.1
> jupyter-events==0.10.0
> jupyter-lsp==2.2.5
> jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1716472197302/work
> jupyter_core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1710257447442/work
> jupyter_server==2.14.1
> jupyter_server_terminals==0.5.3
> jupyterlab==4.2.3
> jupyterlab_pygments==0.3.0
> jupyterlab_server==2.27.2
> jupyterlab_widgets==3.0.11
> kiwisolver==1.4.5
> legacy-api-wrap==1.4
> lightning-cloud==0.5.70
> lightning-lite==1.8.6
> lightning-utilities==0.11.3.post0
> llvmlite==0.43.0
> louvain==0.8.2
> Markdown==3.6
> markdown-it-py==3.0.0
> MarkupSafe==2.1.5
> matplotlib==3.9.0
> matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1713250518406/work
> mdurl==0.1.2
> mistune==3.0.2
> ml-dtypes==0.4.0
> ml_collections==0.1.1
> mpmath==1.3.0
> msgpack==1.0.8
> mudata==0.2.4
> multidict==6.0.5
> multipledispatch==1.0.0
> mypy-extensions==1.0.0
> natsort==8.4.0
> nbclient==0.10.0
> nbconvert==7.16.4
> nbformat==5.10.4
> nest_asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1705850609492/work
> networkx==3.2.1
> notebook==7.2.1
> notebook_shim==0.2.4
> numba==0.60.0
> numpy==1.26.4
> numpyro==0.15.0
> nvidia-cublas-cu12==12.1.3.1
> nvidia-cuda-cupti-cu12==12.1.105
> nvidia-cuda-nvrtc-cu12==12.1.105
> nvidia-cuda-runtime-cu12==12.1.105
> nvidia-cudnn-cu12==8.9.2.26
> nvidia-cufft-cu12==11.0.2.54
> nvidia-curand-cu12==10.3.2.106
> nvidia-cusolver-cu12==11.4.5.107
> nvidia-cusparse-cu12==12.1.0.106
> nvidia-nccl-cu12==2.20.5
> nvidia-nvjitlink-cu12==12.5.40
> nvidia-nvtx-cu12==12.1.105
> omegaconf==2.3.0
> openpyxl==3.1.5
> opt-einsum==3.3.0
> optax==0.2.1
> orbax-checkpoint==0.5.20
> ordered-set==4.1.0
> orjson==3.10.6
> overrides==7.7.0
> packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1718189413536/work
> pandas==1.5.0
> pandocfilters==1.5.1
> parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1712320355065/work
> patsy==0.5.6
> pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1706113125309/work
> pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
> pillow==10.3.0
> platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1715777629804/work
> plotly==5.22.0
> prometheus_client==0.20.0
> prompt_toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1718047967974/work
> protobuf==3.20.1
> psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1719274564771/work
> ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
> pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
> pycparser==2.22
> pydantic==1.10.17
> pydantic_core==2.4.0
> pyDeprecate==0.3.0
> Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1714846767233/work
> PyJWT==2.8.0
> pynndescent==0.5.13
> pyparsing==3.1.2
> pyro-api==0.1.2
> pyro-ppl==1.8.0
> python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1709299778482/work
> python-dotenv==1.0.1
> python-json-logger==2.0.7
> python-multipart==0.0.9
> pytorch-lightning==1.3.8
> pytz==2024.1
> PyYAML==5.4.1
> pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1715024408309/work
> readchar==4.1.0
> record-keeper==0.9.32
> referencing==0.35.1
> requests==2.32.3
> rfc3339-validator==0.1.4
> rfc3986-validator==0.1.1
> rich==13.7.1
> rpds-py==0.18.1
> runs==1.2.2
> s3fs==2023.12.2
> s3transfer==0.10.2
> scanpy==1.10.2
> scikit-learn==1.5.0
> scikit-learn-intelex==2024.5.0
> scikit-misc==0.3.1
> scipy==1.13.1
> scvi-tools==0.14.0
> seaborn==0.13.2
> Send2Trash==1.8.3
> session_info==1.0.0
> shellingham==1.5.4
> simplejson==3.19.2
> six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
> sniffio==1.3.1
> sortedcontainers==2.4.0
> soupsieve==2.5
> sparse==0.15.4
> stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
> starlette==0.22.0
> starsessions==1.3.0
> statsmodels==0.14.2
> stdlib-list==0.10.0
> sympy==1.12.1
> tbb==2021.13.0
> tenacity==8.4.2
> tensorboard==2.17.0
> tensorboard-data-server==0.7.2
> tensorstore==0.1.63
> termcolor==2.4.0
> terminado==0.18.1
> texttable==1.7.0
> threadpoolctl==3.5.0
> tinycss2==1.3.0
> tomli==2.0.1
> toolz==0.12.1
> torch==1.10.2+cu113
> torchmetrics==0.6.0
> torchvision==0.11.3
> tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1717722887379/work
> tqdm==4.66.4
> traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1713535121073/work
> triton==2.3.1
> typed-argument-parser==1.10.0
> typer==0.12.3
> types-python-dateutil==2.9.0.20240316
> typing-inspect==0.9.0
> typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1717802530399/work
> tzdata==2024.1
> ujson==5.10.0
> umap-learn==0.5.6
> uri-template==1.3.0
> urllib3==1.26.19
> uvicorn==0.30.1
> uvloop==0.19.0
> watchfiles==0.22.0
> wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1704731205417/work
> webcolors==24.6.0
> webencodings==0.5.1
> websocket-client==1.8.0
> websockets==11.0.3
> Werkzeug==3.0.3
> widgetsnbextension==4.0.11
> wrapt==1.16.0
> xarray==2024.3.0
> xmod==1.8.1
> yarl==1.9.4
> zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1718013267051/work
> ```

Hi @jlr13 ,

Do you install these packages in a python 3.8 environment? Also I am curious what versions are you using for those self-built libraries. I am having trouble installing packages in this file.

Thanks,
Wei
