### ISSUE TITLE
Can I integrate two mouse datasets together?

### ISSUE THREAD

**Issue by vishnums007** [snap-stanford/SATURN#64]
Hi @Yanay1 ,
I am working with  a cross species comparison of zebrafish vs mouse and I have two mouse datasets and one zebrafish dataset. I was wondering what is the best way to integrate all three together? At end, I would also like to know how well the mouse datasets integrated together as well as mouse vs zebrafish. 

Regards, 
Vishnu

**Comment by Yanay1** [comment]
Yes you can!

There are a few different options, one is to combine both mouse datasets into one anndata, and the other is to keep them separate. You could also integrate each mouse dataset with the zebrafish dataset separately. 

It might be worth trying all these options to see which works the best for you
