### ISSUE TITLE
Can I use spatial transcriptome data as input data?

### ISSUE THREAD

**Issue by jekim2022** [snap-stanford/SATURN#65]
Hello, thank you for developing a great tool!

I'm going to use this amazing tool to analyze the gene expression correlation between human cell scRNA-seq data and mouse spatial transcriptome data. 

Is it possible for input data to use spatial transcriptome data with spot-specific IDs (rather than single-cell IDs)?
I'm asking because the spatial transcriptome data has a much smaller number of IDs (also a smaller number of features) than scRNA-seq data, so I'm worried that the accuracy of applying SATURN will be significantly reduced or there will be another unexpected problems.

Could you please advise if there is any need for special correction or precautions in the case of using spatial transcriptome data as input in pairs with scRNA-seq data?

Thank you in advance.
I'll be waiting for your reply!

Best, 
JIeun

**Comment by Yanay1** [comment]
Hi, there shouldn't be an issue with using ST data.

Given that there is a smaller number of features overall, you might want to use fewer macrogenes.

Another option is to use our UCE method: https://github.com/snap-stanford/UCE
