### ISSUE TITLE
Program running killed without errors

### ISSUE THREAD

**Issue by yilevine** [snap-stanford/SATURN#66]
Hi,

I am trying to run SATURN on the integration of human and pig data. I successfully ran the tutorial in the Vignettes/frog_zebrafish_embryogenesis/Train SATURN.ipynb. When I ran SATURN on my data. The running was just killed without any errors.
### The code I used is below:
`python3 code/train-saturn.py --in_data=data/saturn/run_hu_ss.csv --in_label_col=manual_anno --ref_label_col=manual_anno --num_macrogenes=2000 --hv_genes=8000 --centroids_init_path=results/saturn/hp_centroids.pkl --score_adata --ct_map_path=data/saturn/cell_type_map_hu_ss.csv --work_dir=results/saturn --device_num=0`
### The running output is 
`Global seed set to 0 
Using Device 0
Set seed to 0
After loading the anndata human View of AnnData object with n_obs × n_vars = 53686 × 17384
...
After loading the anndata pig View of AnnData object with n_obs × n_vars = 85375 × 13350
...
Killed`

I am using A100 (80G)

Any idea about the error?

Thanks 
Yile

**Comment by Yanay1** [comment]
Hi, I think the crash could be happening because of the system running out of memory when creating the centroids, which is unrelated to the GPU.

**Comment by yilevine** [comment]
Hi, 

Thanks for the reply.
Okay. I will try a bigger memory on the hpc.
I am closing it.

Thanks
Yile
