### ISSUE TITLE
One of the species is experiencing this issue; can not create XXX.pkl

### ISSUE THREAD

**Issue by Joyce121** [snap-stanford/SATURN#69]
![010101](https://github.com/user-attachments/assets/c494e4b9-6f17-4e07-bc58-e8ba15f1453d)

**Comment by Joyce121** [comment]
I don't know which file is causing the issue; all species follow the same procedure. Can you help me ?

**Comment by Yanay1** [comment]
Please double check that your input expression matrix does not contain NaN values for any genes.
