### ISSUE TITLE
pretrain error

### ISSUE THREAD

**Issue by huawen-poppy** [snap-stanford/SATURN#7]
Hello! Thanks for your wonderful tool! Recently, I am trying to use the tool to integrate two species. But there was an error stating that:

> File "./SATURN/protein_embeddings/../train-saturn.py", line 205, in pretrain_saturn
    for species in np.random.choice(sorted_species_names, size=len(sorted_species_names), replace=False):
KeyError: 'tricho'

This error occurred because in the pretrain_loader, some keys in batch_dict only contain one species information. Why did this happen? Is it normal when dealing with two phyllo-distantly species?

**Comment by Yanay1** [comment]
This might happen if the number of cells from one species is much smaller than the other species or if the batch size is very small. How many cells from each species are you using and what batch size?

**Comment by huawen-poppy** [comment]
Thanks for your quick response! I used the default batch size. There are 4600 cells in one species and 344k cells in another species. Does this affect influence the integration? How can I avoid any potential drawbacks?

**Comment by Yanay1** [comment]
I'm not sure why this might be happening, it could be that somehow because of the size disparity between the two species, there are batches that don't have any cells from the smaller species but that seems unlikely.  

What does the output of SATURN look like before the error occurs?

**Comment by huawen-poppy** [comment]
The output looks like below:
```
Epoch 38: L1 Loss 0.0 Rank Loss 66.51234436035156, Avg Loss chick: 487, Avg Loss tricho: 548:  19%|█▉        | 38/200 [19:14<1:22:26, 30.53s/it]
^MEpoch 38: L1 Loss 0.0 Rank Loss 66.51234436035156, Avg Loss chick: 487, Avg Loss tricho: 548:  19%|█▉        | 38/200 [19:44<1:24:10, 31.17s/it]
```

**Comment by Yanay1** [comment]
Can you please try replacing:

`sorted_species_names`

in that line with 

`list(batch_dict.keys()`

Thanks!

**Comment by Yanay1** [comment]
Closing this for now, please reopen if you are still having this issue!
