### ISSUE TITLE
Installation issue with torch, version

### ISSUE THREAD

**Issue by eisascience** [snap-stanford/SATURN#71]
Hi,
I wish this package had a conda script ready to go. Nonetheless, I got the requirements installed, but running the below step fails.
Any suggestions? Perhaps updates are needed?

pip install torch==1.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
Looking in links: https://download.pytorch.org/whl/cu113/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.10.2+cu113 (from versions: 1.11.0, 1.11.0+cu113, 1.12.0, 1.12.0+cu113, 1.12.1, 1.12.1+cu113, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1)
ERROR: No matching distribution found for torch==1.10.2+cu113

----
FYI upstream of this I had done:

conda create -n OMICsPy_SATURN python=3.10 pip
conda activate OMICsPy_SATURN

#Download the requirements.txt from github
pip install -r requirements.txt

**Comment by eisascience** [comment]
Trying the next available, i.e.,
pip install torch==1.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

It seems to install but with issues:
Looking in links: https://download.pytorch.org/whl/cu113/torch_stable.html
Collecting torch==1.11.0+cu113
  Downloading https://download.pytorch.org/whl/cu113/torch-1.11.0%2Bcu113-cp310-cp310-linux_x86_64.whl (1637.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 GB 52.2 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in /home/groups/ConradLab/Eisa/anaconda3/OMICsPy_SATURN/lib/python3.10/site-packages (from torch==1.11.0+cu113) (4.12.2)
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 2.4.1
    Uninstalling torch-2.4.1:
      Successfully uninstalled torch-2.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lightning 2.1.4 requires torch<4.0,>=1.12.0, but you have torch 1.11.0+cu113 which is incompatible.
pyro-ppl 1.9.1 requires torch>=2.0, but you have torch 1.11.0+cu113 which is incompatible.
pytorch-lightning 2.4.0 requires torch>=2.1.0, but you have torch 1.11.0+cu113 which is incompatible.
torchvision 0.19.1 requires torch==2.4.1, but you have torch 1.11.0+cu113 which is incompatible.
Successfully installed torch-1.11.0+cu113

**Comment by Yanay1** [comment]
Newer versions of torch do work, we've tested up to `torch==2.3.1`. Make sure that the cuda version matches your installed version of cuda.
