### ISSUE TITLE
TypeError: descriptor 'union' of 'set' object needs an argument when generate protein embedding

### ISSUE THREAD

**Issue by zhuojiuqingyun** [snap-stanford/SATURN#76]
Dear authors,
Thank you very much for making this great tool.
I got the following error while running Generate Protein Embeddings.ipynb using my protein fasta.
```
!python map_gene_symbol_to_protein_ids.py \
    --fasta_path ./data/{NAME}.fa \
    --save_path ./data/{NAME}.gene_symbol_to_protein_ID.json


!python convert_protein_embeddings_to_gene_embeddings.py \
    --embedding_dir ./data/{NAME}.clean.fa_esm2 \
    --gene_symbol_to_protein_ids_path ./data/{NAME}.gene_symbol_to_protein_ID.json \
    --embedding_model ESM2 \
    --save_path ./data/{NAME}.gene_symbol_to_embedding_ESM2.pt
```
```
100%|█████████████████████████████████| 28010/28010 [00:00<00:00, 673321.35it/s]
28010
Traceback (most recent call last):
  File "map_gene_symbol_to_protein_ids.py", line 63, in <module>
    map_gene_symbol_to_protein_ids(Args().parse_args())
  File "map_gene_symbol_to_protein_ids.py", line 46, in map_gene_symbol_to_protein_ids
    all_protein_ids = set.union(*[protein_ids for protein_ids in gene_symbol_to_protein_ids.values()])
TypeError: descriptor 'union' of 'set' object needs an argument
Traceback (most recent call last):
  File "convert_protein_embeddings_to_gene_embeddings.py", line 86, in <module>
    convert_protein_embeddings_to_gene_embeddings(Args().parse_args())
  File "convert_protein_embeddings_to_gene_embeddings.py", line 27, in convert_protein_embeddings_to_gene_embeddings
    with open(args.gene_symbol_to_protein_ids_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/xenia.proteins.gene_symbol_to_protein_ID.json'
```
I didn't encounter this error when I running the example Xenopus_tropicalis. Could you help me with my issue?

Yours sincerely.
Ruijie

**Comment by Yanay1** [comment]
Please double check and make sure the path is correct:
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/xenia.proteins.gene_symbol_to_protein_ID.json'
```
The error is due to no file existing at that location.

**Comment by zhuojiuqingyun** [comment]
> Please double check and make sure the path is correct:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'data/xenia.proteins.gene_symbol_to_protein_ID.json'
> ```
> 
> The error is due to no file existing at that location.

Thanks for your reply. 
In fact, it's this error which led to  data/xenia.proteins.gene_symbol_to_protein_ID.json not being generated.
`TypeError: descriptor 'union' of 'set' object needs an argument`
I think the reason is that I couldn't find the protein fasta from ensembl, so I downloaded from NCBI. So my protein fasta description doesn't contain gene symbol and protein id ,which caused the error above.
How can I generate protein embedding from protein fasta not downloaded from Ensembl? Could you give me some instructions?

Thanks a lot!

Ruijie

**Comment by zhuojiuqingyun** [comment]
Moreover, I want to use SATURN for Xenia to cross species annotate，but we don't know the exact gene_symbol of related protein_id. How can I generate embedding for SATURN？
For example, the description of my protein fasta and part of gtf are as follows.
```
>Xe_029168-T1 Xe_029168
MSSTEEEVEFDIEYIATEVQPYMFEPLASSNNVETDEDLSSSSSTDSSSDEYTHRIGNTNWCECGHCVAMTTGRESICCHEEPKTDPKIHGDHLCIT
```
`HiC_scaffold_1  GenBank CDS     333245  333499  .       -       0       transcript_id "Xe_000054-T1"; gene_id "Xe_000054";`
Could you give me some advices? Thank you very much!

**Comment by camiel-m** [comment]
The problem here is that many protein fastas don't have gene symbols in the sequence headers and instead just have the gene_id (gene:). You can either add the gene_id as gene_symbol to your fasta or set GENE_SYMBOL to 'gene:' in map_gene_symbol_to_protein_ids.py. Most likely your anndata objects are also using the gene_ids instead of gene symbols for the row attributes anyway.

A simple fix for this would be to add GENE_SYMBOL as an argument to the script 
```
"""Script to map gene symbol to protein IDs based on Ensembl FASTA files."""
import json
from collections import defaultdict
from pathlib import Path

from Bio import SeqIO
from tap import Tap
from tqdm import tqdm


class Args(Tap):
    fasta_path: Path  # Path to FASTA protein sequence file from Ensembl.
    save_path: Path  # Path to a .json file where the mapping from gene symbol to protein IDs will be saved.    
    GENE_SYMBOL: str = 'gene_symbol:' # name of attribute to be used to identify genes

    def process_args(self) -> None:
        self.save_path.parent.mkdir(parents=True, exist_ok=True)

def map_gene_symbol_to_protein_ids(args: Args) -> None:
    """Script to map gene symbol to protein IDs based on Ensembl FASTA files."""

    GENE_SYMBOL = args.GENE_SYMBOL
    print(f"Using '{GENE_SYMBOL}' to identify genes")
```
