### ISSUE TITLE
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

### ISSUE THREAD

**Issue by Quianter** [snap-stanford/SATURN#77]
Hi:
    SATURN's programmer
    when i run train-saturn.py to integrate my cross-species scRNA dataset, I met a error message that doesn't stop the whole program: 
"*****PRETRAIN SCORES*****
-------------------------
------Log Reg Scores-----
/PATH/TO/MY/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT." 
     And, it looks like a failure when get_all_scores script tried to convergent, how can i improve the ITERATIONS number by adjust the default parameter, like --polling_freq or --pretrain_epochs?

**Comment by Yanay1** [comment]
Hi,

This is just a warning about the classifier used to score the alignments, it shouldn't change results. 

To change this you would edit this line:

https://github.com/snap-stanford/SATURN/blob/6906abf23728aa8ebf400cedf4ce38e4821a0a49/score_adata.py#L839
and add an argument `max_iter=` to the initialization of the logistic classifier model, setting the value to something above the default 100, like to 200.

However, I don't think this is needed.
