### ISSUE TITLE
Gene Reduction in the provided Datasets Using ESM1b Protein Language Model

### ISSUE THREAD

**Issue by Sporgelum** [snap-stanford/SATURN#79]
Dear SATURN Development Team,

First, I would like to thank you for your excellent work on SATURN. The tool is very promising, and we have found it extremely useful for our analysis.

However, we encountered an unexpected issue that seems to have very little  documentation or explanation for.

While working with the ESM1b protein language model, we observed that the single cell datasets we were using for integration, got significantly reduced in terms of number of genes after running train-saturn.py 

In the example datasets with frog and zebrafish, the datasets reduce even more drastically in terms of the number of genes after running train-saturn.py.

Here are the details we observed for the zebrafish and frog:
Zebrafish:
Pre-SATURN
AnnData object with n_obs × n_vars = 63371 × 30032
obs: 'n_counts', 'unique_cell_id', 'cell_names', 'library_id', 'batch', 'ClusterID', 'ClusterName', 'TissueID', 'TissueName', 'TimeID', 'cluster', 'cell_type', 'n_genes'
var: 'n_cells'

Frog:
AnnData object with n_obs × n_vars = 136966 × 26550
obs: 'library', 'clusters', 'dev_stage', 'parent_clusters', 'cell_type'

Post-SATURN:
After loading the anndata frog View of AnnData object with n_obs × n_vars = 96935 × 9538
    obs: 'clusters', 'parent_clusters', 'cell_type', 'n_genes', 'species', 'species_type_label', 'truth_labels', 'ref_labels'
    var: 'n_cells'

After loading the anndata zebrafish View of AnnData object with n_obs × n_vars = 63371 × 16980
    obs: 'n_counts', 'unique_cell_id', 'cell_names', 'library_id', 'batch', 'ClusterID', 'ClusterName', 'TissueID', 'TissueName', 'TimeID', 'cluster', 'cell_type', 'n_genes', 'species', 'species_type_label', 'truth_labels', 'ref_labels'
    var: 'n_cells'

We were wondering if there is any explanation for this reduction, as it seems consistent with both the frog and zebrafish example datasets. If this is an expected behavior, could you kindly provide more details on why this occurs? Could this be solved using another ESM model?  If it’s not expected, do you know if there is a way to resolve or mitigate this gene reduction?

In our datsets we got a similar effect.
Pre:
Species A: AnnData object with n_obs × n_vars = 3091 × 16404
Species B: AnnData object with n_obs × n_vars = 3091 × 20780

After running train-saturn.py

Species A: After loading the anndata View of AnnData object with n_obs × n_vars = 3091 × 12440
Species B: After loading the anndata View of AnnData object with n_obs × n_vars = 3091 × 13271

We appreciate your help and look forward to hearing from you.

PD:  If possible we would be also interested in knowing if there are recommendations from the authors for smaller datasets, in order to proceed with the integration, as we are using non-model species and would like to gain insights for different celltypes. 

Thank you in advance!

Best regards,
Marius

**Comment by Yanay1** [comment]
Thanks!

The way we generated protein embeddings for different species limits gene numbers in 2 steps:

1. First, we can only represent protein coding genes, since we are using protein embeddings
2. Second, we map all spliceforms / different transcripts of the same gene to the same protein based on gene symbol name

Because of these two steps, the overall number of genes gets reduced a lot.

For other small datasets, it is possible that our newer tool, UCE, https://github.com/snap-stanford/UCE could be helpful.
