### ISSUE TITLE
kernel dies while running 'frog = generate_frog_h5ad()' in dataloader.ipynb

### ISSUE THREAD

**Issue by MohammedZidane** [snap-stanford/SATURN#8]
Hi,
When I first ran the dataloader.ipynb, I got this error in the cell calling generate_frog_h5ad() function

MemoryError: Unable to allocate 27.1 GiB for an array with shape (26550, 136966) and data type float64

I solved this by using

echo 1 | sudo tee /proc/sys/vm/overcommit_memory

But unfortunately, the kernel dies. Do you have any suggestions? or how to generate part of the data not all of it? Because my target is to investigate how Saturn works not using it

Thanks!

**Comment by Yanay1** [comment]
Could you send me an email at yanay (at) stanford.edu and I can send you a copy of the already created frog and zebrafish count h5ad files? Thanks!
