### ISSUE TITLE
perform computations on multiple GPUs 

### ISSUE THREAD

**Issue by TransposableElements** [snap-stanford/SATURN#80]
Dear authors,
Thank you very much for making this great tool.
Im new to dl.  I wonder how to perform computations on multiple GPUs. 

in train-saturn.py

    parser.add_argument('--device', type=str,
                    help='Set GPU/CPU')
    parser.add_argument('--device_num', type=int,
                        help='Set GPU Number')

But I don't know how to configure and use multiple GPUs for computation.  ;(

**Comment by Yanay1** [comment]
Hi,

We don't have a multigpu setup for SATURN unfortunately. I would recommend a framework like pytorch lightning if you wish to setup one.

Our newer model, https://github.com/snap-stanford/UCE is multi-gpu enabled using hugging face accelerator.
